GYMONE/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GYMONE.Filters;
using GYMONE.Models;
using GYMONE.Repository;
using PagedList;
namespace GYMONE.Controllers
{
    [HandleError()]
    [MyExceptionHandler]
    [Authorize(Roles = "SystemUser,Admin")]
    public class PaymentController : Controller
    {
        const int RecordsPerPage = 10;

        IPaymentlisting objIPaymentlisting;

        public PaymentController()
        {
            objIPaymentlisting = new Paymentlisting();
        }


        public ActionResult PaymentDetails(PaymentlistingDTOVM model, string SearchButton)
        {
            PaymentlistingDTOVM dto = new PaymentlistingDTOVM();

            if (model.PaymentSearch == null)
            {
                ModelState.AddModelError("Message", "Please select type to search ( Member No / Member Name).");
            }
            else if (model.PaymentSearch == "1" && model.Memberno == null)
            {
                ModelState.AddModelError("Message", "Please Enter Member No.");
            }
            else if (model.PaymentSearch == "2" && model.MemberName == null)
            {
                ModelState.AddModelError("Message", "Please Enter Member Name.");
            }
            else
            {
                if (!string.IsNullOrEmpty(model.SearchButton) || model.Page.HasValue)
                {
                    if (model.Memberno != null)
                    {
                        var Listpay = objIPaymentlisting.AllPaymentDetails(Convert.ToString(model.Memberno));

                        var results = Listpay.Where(p => (p.MemberID == model.Memberno));

                        var pageIndex = model.Page ?? 1;

                        model.SearchResults = results.ToPagedList(pageIndex, RecordsPerPage);
                    }
                    else if (model.MemberName != null)
                    {
                        string[] Memno = model.MemberName.Split('|');

                        var Listpay = objIPaymentlisting.AllPaymentDetails(Convert.ToString(Memno[3]));

                        var results = Listpay.Where(p => (p.MemberID == Convert.ToInt32(Memno[3])));

                        var pageIndex = model.Page ?? 1;

                        model.SearchResults = results.ToPagedList(pageIndex, RecordsPerPage);
                    }
                }
            }

            return View(model);
        }

        public JsonResult GetDatabyMemberNo(string term)
        {
            var list = objIPaymentlisting.ListofMemberNo(term);
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetDatabyMemberName(string term)
        {
            var list = objIPaymentlisting.ListofMemberName(term);
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AllMemberList()
        {
            PaymentlistingDTO dto = new PaymentlistingDTO();
            dto.PaymentList = objIPaymentlisting.AllPaymentDetails();

            return View("AllMemberList", dto);
        }
    }
}

GYMONE/Views/Payment/AllMemberList.cshtml
@model GYMONE.Models.PaymentlistingDTO
@{
    ViewBag.Title = "AllMemberList";
}
@using GridMvc.Html




<script src="~/Scripts/jquery-1.11.1.js"></script>
<link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>
<script src="~/bootstrap/js/bootstrap.min.js"></script>
<link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />


<div class="container">
    <div style="margin-top: 10px"></div>


    <div class="logo col-sm-12 text-center col-md-12 ">
        <img alt="" src="~/Images/dotnetsai.png" />
    </div>

    <div class="clearfix"></div>

    <fieldset>

        <legend class="legend">All Member List</legend>
        <div style="margin-top: 5px"></div>

        <div class="test" style="overflow: scroll; height: 500px; width: 1000px">
            <div style="width: 1000px">

                <div class="panel">

                    <div class="panel-body">


                        @Html.Grid(Model.PaymentList).Columns(columns =>
                    {
                        columns.Add(c => c.MemberReg).Titled("MemberNo").Filterable(true);
                        columns.Add(c => c.Name).Titled("Name").Filterable(true);
                        columns.Add(c => c.JoiningDate).Titled("JoiningDate").Filterable(true).Format("{0:dd/MM/yyyy}");
                        columns.Add(c => c.RenwalDate).Titled("RenwalDate").Filterable(true).Format("{0:dd/MM/yyyy}");
                        columns.Add(c => c.Contactno).Titled("Contactno").Filterable(true);
                        columns.Add(c => c.PlanName).Titled("PlanName").Filterable(true);
                        columns.Add(c => c.SchemeName).Titled("SchemeName").Filterable(true);
                        columns.Add(c => c.PaymentAmount).Titled("Amount").Filterable(true);
 

                    }).WithPaging(10).Sortable(true)
                    </div>
                </div>
            </div>
        </div>
    </fieldset>

</div>

GYMONE/Views/Payment/PaymentDetails.cshtml
@model GYMONE.Models.PaymentlistingDTOVM

@using PagedList.Mvc

@{
    ViewBag.Title = "Payment Details";
}


<script src="~/Scripts/jquery-1.11.1.js"></script>
<script src="~/Scripts/jquery-ui.min.js"></script>
<link href="~/Scripts/jquery-ui.min.css" rel="stylesheet" />
<script src="~/bootstrap/js/bootstrap.min.js"></script>
<link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />


<script type="text/javascript">
    $(document).ready(function () {
        $("#txtMemberno").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: "/Payment/GetDatabyMemberNo",
                    type: "POST",
                    dataType: "json",
                    data: { term: request.term },
                    success: function (data) {
                        response($.map(data, function (item) {
                            return { label: item.MemberNo, value: item.MainMemberID };
                        }))

                    }
                })
            },
            messages: {
                noResults: "", results: ""
            }
        });
    })
</script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#txtMemberName").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: "/Payment/GetDatabyMemberName",
                    type: "POST",
                    dataType: "json",
                    data: { term: request.term },
                    success: function (data) {
                        response($.map(data, function (item) {
                            return { label: item.Name, value: item.Name };
                        }))

                    }
                })
            },
            messages: {
                noResults: "", results: ""
            }
        });
    })
</script>

<script type="text/javascript">
    function Checkpanel() {

        if ($("#Memberno").is(':checked')) {

            $("#MDID1").css("display", "block");
            $("#MDID2").css("display", "none");
        }

        if ($("#MemberName").is(':checked')) {

            $("#MDID2").css("display", "block");
            $("#MDID1").css("display", "none");
        }

    }

</script>

<script type="text/javascript">
    $.noConflict();
</script>

<script type="text/javascript">

    function Valdateform() {

        if ($("#Memberno").prop("checked") == false && $("#MemberName").prop("checked") == false) {
            alert('Please select type to search ( Member No / Member Name).');
            return false;
        }
        else if ($("#Memberno").prop("checked") == true && $("#txtMemberno").val() == "") {
            alert('Please Enter Member No.');
            return false;
        }
        else if ($("#MemberName").prop("checked") == true && $("#txtMemberName").val() == "") {
            alert('Please Enter Member Name.');
            return false;
        }
        else {
            return true;
        }

    }

</script>



@using (Html.BeginForm("PaymentDetails", "Payment", FormMethod.Get))
{
    
        
    <div class="container">
        <div style="margin-top: 10px"></div>


        <div class="logo col-sm-12 text-center col-md-12 ">
        <img alt="" src="~/Images/dotnetsai.png" />
    </div>

    <div class="clearfix"></div>


        <fieldset>
            <legend class="legend">Payment Details</legend>

            <div class="panel">

                <div class="panel-body">









                    <div class="row">
                        <div class="col-md-12">

                            @Html.RadioButtonFor(m => m.PaymentSearch, 1, new { id = "Memberno", onclick = "Checkpanel();" }) Member No
                    @Html.RadioButtonFor(m => m.PaymentSearch, 2, new { id = "MemberName", onclick = "Checkpanel();" }) Member Name
                 
                        </div>
                    </div>
                    <div style="margin-top: 30px"></div>
                    <div style="display: none;" id="MDID1">
                        <div class="row">
                            <div class="col-md-3">
                                @Html.Label("Memberno")
                            </div>
                            <div class="col-md-3">
                                @Html.TextBoxFor(m => m.Memberno, new { id = "txtMemberno", @class = "form-control" })
                            </div>
                            <div class="col-md-3">
                            </div>
                            <div class="col-md-3">
                            </div>
                        </div>
                    </div>
                    <div style="margin-top: 5px"></div>
                    <div style="display: none;" id="MDID2">
                        <div class="row">
                            <div class="col-md-3">
                                @Html.Label("MemberName")
                            </div>
                            <div class="col-md-3">
                                @Html.TextBoxFor(m => m.MemberName, new { id = "txtMemberName", @class = "form-control" })
                            </div>
                            <div class="col-md-3">
                            </div>
                            <div class="col-md-3">
                            </div>
                        </div>
                    </div>
                    <div style="margin-top: 5px"></div>
                    <div class="row">
                        <div class="col-md-12">
                            <input type="submit" onclick="return Valdateform();" class="btn btn-success" name="SearchButton" value="Search" />
                             @Html.ActionLink("Cancel", "PaymentDetails", "Payment", new  {  @class="btn btn-success"})
                        </div>
                    </div>
                    <div style="margin-top: 5px"></div>
                    <div class="row">
                        <div >
                            <div class="clearfix"></div>
                            <div id="gridContent" style="padding: 20px;">
                                @if (Model.SearchResults != null && Model.SearchResults.Count > 0)
                                {



                                    var grid = new WebGrid(Model.SearchResults, defaultSort: "DeveloperCount");
                                    @grid.GetHtml(
           tableStyle: "webgrid-table",
        headerStyle: "webgrid-header",
        footerStyle: "webgrid-footer",
        alternatingRowStyle: "webgrid-alternating-row",
        selectedRowStyle: "webgrid-selected-row",
        rowStyle: "webgrid-row-style",
        mode: WebGridPagerModes.All,
            columns: grid.Columns(
            grid.Column("MemberReg", "MemberReg"),
            grid.Column("Name", header: "NAME", style: "300px"),
            grid.Column("Contactno", "Contactno"),
            grid.Column("PlanName", "PlanName"),
            grid.Column("SchemeName", "SchemeName"),
            
            grid.Column("PaymentAmount", "PaymentAmount"),


grid.Column(
    "JoiningDate",
    "JoiningDate",
    format: (item) => string.Format("{0:dd-MMM-yyyy}", item.JoiningDate)
),
grid.Column(
    "RenwalDate",
    "RenwalDate",
    format: (item) => string.Format("{0:dd-MMM-yyyy}", item.RenwalDate)
)


            ))
  
                                    if (Model.SearchResults != null && Model.SearchResults.Count > 0)
                                    {
                                    @Html.PagedListPager(Model.SearchResults, page => Url.Action("PaymentDetails", new RouteValueDictionary() 
              {
              { "Page", page },
              { "PaymentSearch", Model.PaymentSearch },
              { "Memberno", Model.Memberno },
              { "MemberName", Model.MemberName }
              }), PagedListRenderOptions.PageNumbersOnly)
                                    }
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>



    </div>
    

}


<script type="text/javascript">
    function rebindpanel() {


        if ('@Model.PaymentSearch' == '1') {

            document.getElementById("MDID1").style.display = "block";
            document.getElementById("MDID2").style.display = "none";
        }

        else if ('@Model.PaymentSearch' == '2') {

            document.getElementById("MDID2").style.display = "block";
            document.getElementById("MDID1").style.display = "none";
        }
        else {

            document.getElementById("MDID1").style.display = "none";
            document.getElementById("MDID2").style.display = "none";

        }

    }

    window.onload = rebindpanel();
</script>


