GYMONE/Models/RenewalSearch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GYMONE.Models
{
    public class RenewalSearch
    {
        public string SearchButton { get; set; }
        public string RenewalSearchID { get; set; }
        public string Fromdate { get; set; }
        public string Todate { get; set; }
        public string Exactdate { get; set; }
    }
}

GYMONE/Controllers/RenewalSearchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CrystalDecisions.CrystalReports.Engine;
using GYMONE.Models;
using GYMONE.Repository;

namespace GYMONE.Controllers
{
    public class RenewalSearchController : Controller
    {
        IlReports objIRecepit;


        public RenewalSearchController()
        {
            objIRecepit = new ReportsMaster();

        }

        [HttpGet]
        public ActionResult RenewalReport()
        {
            TempData["Message"] = null;
            return View(new RenewalSearch());
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RenewalReport(RenewalSearch obj, string actionType)
        {

            if (string.Equals(actionType, "Download"))
            {
                if (!string.IsNullOrEmpty(obj.Exactdate))
                {
                    obj.Fromdate = null;
                    obj.Todate = null;
                }
                else if (!string.IsNullOrEmpty(obj.Fromdate) && !string.IsNullOrEmpty(obj.Todate))
                {
                    obj.Exactdate = "1990-01-01 00:00:00.000";
                }
                if (string.IsNullOrEmpty(obj.RenewalSearchID))
                {
                    ModelState.AddModelError("Error", "Please select By Exact Date or By Between Date !");
                }
                else if (string.IsNullOrEmpty(obj.Exactdate) && obj.RenewalSearchID == "1")
                {
                    ModelState.AddModelError("Error", "Please enter Exact date!");
                }
                else if (string.IsNullOrEmpty(obj.Fromdate) && obj.RenewalSearchID == "2")
                {
                    ModelState.AddModelError("Error", "Please enter From date!");
                }
                else if (string.IsNullOrEmpty(obj.Todate) && obj.RenewalSearchID == "2")
                {
                    ModelState.AddModelError("Error", "Please enter To date!");
                }
                else
                {




                    DataSet ds = objIRecepit.Get_RenewalReport(obj);
                    ds.Tables[0].TableName = "RecepitDataset";

                    if (ds.Tables[0].Rows.Count > 0)
                    {


                        ReportClass rptH = new ReportClass();
                        rptH.FileName = Server.MapPath("~/Reports/ExactDate.rpt");
                        rptH.Load();
                        rptH.SetDataSource(ds.Tables[0]);
                        Response.Buffer = false;
                        Response.ClearContent();
                        Response.ClearHeaders();

                        Stream stream = rptH.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                        stream.Seek(0, SeekOrigin.Begin);
                        return File(stream, "application/pdf", "RenewalReport.pdf");
                    }
                }
            }

            return View(obj);
        }

    }
}

GYMONE/Views/RenewalSearch/RenewalReport.cshtml
@model GYMONE.Models.RenewalSearch
@{
    ViewBag.Title = "GenerateRecepit";
}




<script src="~/Scripts/jquery-1.11.1.js"></script>
<script src="~/Scripts/jquery-ui.min.js"></script>
<script src="~/bootstrap/js/bootstrap.min.js"></script>
<link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/Scripts/jquery-ui.min.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />







<script type="text/javascript">
    function Checkpanel() {

        if ($("#ByExactDate").is(':checked')) {

            $("#MDID1").css("display", "block");
            $("#MDID2").css("display", "none");
            document.getElementById("Exactdate").value = "";

        }

        if ($("#ByBetweenDate").is(':checked')) {

            $("#MDID2").css("display", "block");
            $("#MDID1").css("display", "none");

            document.getElementById("Fromdate").value = "";
            document.getElementById("Todate").value = "";
        }
    }

</script>


<script type="text/javascript">
    $.noConflict();
</script>

<div class="container">
    <div style="margin-top: 10px"></div>
    <fieldset>

        <legend class="legend">Renewal Report</legend>
       
        <div class="panel">

            <div class="panel-body">


                @if (TempData["Message"] != null)
                {
                    <div class="alert alert-success" style="float: none;" role="alert">
                        <b>@TempData["Message"]</b>
                    </div>
                }


                @using (Html.BeginForm("RenewalReport", "RenewalSearch", FormMethod.Post))
                {
            
                    @Html.ValidationSummary()
                     @Html.AntiForgeryToken()
            
                    <div style="margin-top: 5px"></div>
                    <div class="row">
                        <div class="col-md-12">

                            @Html.RadioButtonFor(m => m.RenewalSearchID, 1, new { id = "ByExactDate", onclick = "Checkpanel();" }) By Exact Date
                @Html.RadioButtonFor(m => m.RenewalSearchID, 2, new { id = "ByBetweenDate", onclick = "Checkpanel();" }) By Between Date
                 
                        </div>
                    </div>
                    <div style="margin-top: 30px"></div>
                    <div style="display: none;" id="MDID1">
                        <div class="row">
                            <div class="col-md-3">
                                @Html.Label("Exact date")
                            </div>
                            <div class="col-md-3">
                                @Html.TextBoxFor(m => m.Exactdate, "{0:yyyy-MM-dd}", new { @class = "form-control", @readonly = true })
                            </div>
                            <div class="col-md-3">
                            </div>
                            <div class="col-md-3">
                            </div>
                        </div>
                    </div>
                    <div style="margin-top: 5px"></div>
                    <div style="display: none;" id="MDID2">
                        <div class="row">
                            <div class="col-md-3">
                                @Html.Label("From date")
                            </div>
                            <div class="col-md-3">
                                @Html.TextBoxFor(m => m.Fromdate, "{0:yyyy-MM-dd}", new { @class = "form-control", @readonly = true })
                            </div>
                            <div class="col-md-3">
                                @Html.Label("To date")
                            </div>
                            <div class="col-md-3">
                                @Html.TextBoxFor(m => m.Todate, "{0:yyyy-MM-dd}", new { @class = "form-control", @readonly = true })
                            </div>
                        </div>
                    </div>
                    <div style="margin-top: 5px"></div>
                    <div class="row">
                        <div class="col-md-12">
                            <input id="DownloadRecepit" class="btn btn-success" onclick="return validatepage();" type="submit" name="actionType" value="Download" />
                            @Html.ActionLink("Cancel", "RenewalReport", "RenewalSearch", new  {  @class="btn btn-success"})
                        </div>
                    </div>
                    <div style="margin-top: 5px"></div>
                }

            </div>

        </div>

    </fieldset>

</div>
<script type="text/javascript">
    function rebindpanel() {
        if ('@Model.RenewalSearchID' == '1') {

            document.getElementById("MDID1").style.display = "block";
            document.getElementById("MDID2").style.display = "none";



        }
        else if ('@Model.RenewalSearchID' == '2') {

            document.getElementById("MDID2").style.display = "block";
            document.getElementById("MDID1").style.display = "none";


        }
        else {
            document.getElementById("MDID1").style.display = "none";
            document.getElementById("MDID2").style.display = "none";
            document.getElementById("Fromdate").value = "";
            document.getElementById("Todate").value = "";
        }
    }
    window.onload = rebindpanel();
</script>

<script>

    function validatepage() {

        if ($("#ByExactDate").is(':checked') == false && $("#ByBetweenDate").is(':checked') == false) {
            alert("Please select By Exact Date or By Between Date !");
            return false;
        }
        else if ($("#ByExactDate").is(':checked') == true && $("#Exactdate").val() == "") {
            alert("Please enter Exact date !");
            return false;
        }
        else if ($("#ByBetweenDate").is(':checked') == true && $("#Fromdate").val() == "") {
            alert("Please enter From date!");
            return false;
        }
        else if ($("#ByBetweenDate").is(':checked') == true && $("#Todate").val() == "") {
            alert("Please enter To date!");
            return false;
        }
        else {

            return true;
        }

    }

</script>
@section Scripts {

    <script src="~/Scripts/jquery-ui.js"></script>

    @Styles.Render("~/Content/themes/base/css")

    <script type="text/javascript">
        $(document).ready(function () {
            $("#Exactdate").datepicker({
                changeMonth: true,
                changeYear: true,
                dateFormat: 'yy-mm-dd'
            });
        });
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#Fromdate").datepicker({
                changeMonth: true,
                changeYear: true,
                dateFormat: 'yy-mm-dd'
            });
        });
    </script>


    <script type="text/javascript">
        $(document).ready(function () {
            $("#Todate").datepicker({
                changeMonth: true,
                changeYear: true,
                dateFormat: 'yy-mm-dd'
            });
        });
    </script>



}